import { Link } from 'react-router-dom';

const services = [
  {
    icon: '🔍',
    title: 'Job Search & Discovery',
    desc: 'Search across job listings using keywords, location, and filters. Results are enriched with AI analysis so you can focus on the best opportunities.',
    highlights: ['Keyword & location search', 'Real-time job scraping', 'Save & track listings'],
  },
  {
    icon: '🎯',
    title: 'AI Job Matching',
    desc: 'Upload your resume and get an instant compatibility score for any job. Our AI identifies matched skills, missing skills, and gives actionable recommendations.',
    highlights: ['Match score (0-100%)', 'Skill gap analysis', 'Actionable recommendations'],
  },
  {
    icon: '📄',
    title: 'Resume Optimization',
    desc: 'Paste your resume and a target job description — our AI rewrites and optimizes your resume to maximize ATS compatibility and recruiter appeal.',
    highlights: ['ATS-friendly formatting', 'Keyword optimization', 'Before/after scoring'],
  },
  {
    icon: '🎤',
    title: 'Interview Preparation',
    desc: 'Get role-specific interview questions generated by AI. Practice answering them and receive detailed feedback with strengths, weaknesses, and improvement tips.',
    highlights: ['Role-tailored questions', 'Answer evaluation', 'Score & feedback'],
  },
  {
    icon: '📊',
    title: 'Application Dashboard',
    desc: 'Keep track of every application you submit. View statuses, match scores, and trends over time from a single unified dashboard.',
    highlights: ['Status tracking', 'Analytics overview', 'Recent activity feed'],
  },
  {
    icon: '🔐',
    title: 'Secure Authentication',
    desc: 'JWT-based authentication keeps your data safe. Your resumes, applications, and interview history are private and encrypted.',
    highlights: ['JWT token auth', 'Password hashing', 'Per-user data isolation'],
  },
];

export default function ServicesPage() {
  return (
    <div className="landing-page">
      <section className="page-hero">
        <span className="hero-badge">Platform Features</span>
        <h1 className="hero-title">
          Powerful Tools for<br />
          <span className="gradient-text">Every Step of Your Search</span>
        </h1>
        <p className="hero-subtitle" style={{ maxWidth: 660, margin: '0 auto' }}>
          Each feature is designed to give you an unfair advantage in the job market,
          powered by AI and built for speed.
        </p>
      </section>

      <section className="landing-section">
        <div className="services-list">
          {services.map((s, i) => (
            <div key={s.title} className={`service-row ${i % 2 === 1 ? 'service-row-reverse' : ''}`}>
              <div className="service-info">
                <div className="feature-icon">{s.icon}</div>
                <h3>{s.title}</h3>
                <p>{s.desc}</p>
                <ul className="service-highlights">
                  {s.highlights.map((h) => (
                    <li key={h}>
                      <span className="highlight-check">✓</span> {h}
                    </li>
                  ))}
                </ul>
              </div>
              <div className="service-visual">
                <div className="service-mockup">
                  <div className="mockup-bar">
                    <span className="mockup-dot" />
                    <span className="mockup-dot" />
                    <span className="mockup-dot" />
                  </div>
                  <div className="mockup-body">
                    <div className="mockup-icon">{s.icon}</div>
                    <div className="mockup-title">{s.title}</div>
                    <div className="mockup-lines">
                      <div className="mockup-line" style={{ width: '80%' }} />
                      <div className="mockup-line" style={{ width: '60%' }} />
                      <div className="mockup-line" style={{ width: '70%' }} />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>

      <section className="cta-section">
        <div className="cta-content">
          <h2>Experience All Features Today</h2>
          <p>Create a free account and start optimizing your job search in minutes.</p>
          <Link to="/register" className="btn-landing btn-landing-primary btn-landing-lg">
            Get Started Free
          </Link>
        </div>
      </section>

      <footer className="landing-footer">
        <div className="footer-bottom">
          &copy; {new Date().getFullYear()} Job Search AI. Built with React, Flask &amp; AI.
        </div>
      </footer>
    </div>
  );
}
